version: "3.5"
services:
  gogen:
    build:
      context: gogen
    command: start-training
  cribl:
    build:
      context: cribl
    ports:
    - 9000:9000
    volumes:
    - ./cribl/master/groups:/opt/cribl/groups
    - ./cribl/master/local:/opt/cribl/local
  cribl-w0:
    build:
      context: cribl
    ports:
    - 9002:9000
    - 10200:10200
    - 10088:10088
    - 10080:10080
    - 10001:10001
    - 9999:9999
    - 5140:5140
    environment:
    - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl:4200
  cribl-w1:
    build:
      context: cribl
    ports:
    - 9003:9000
    - 8125:8125
    - 8125:8125/udp
    environment:
    - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl:4200?tag=metrics
  splunk:
    build:
      context: splunk
    ports:
    - 8000:8000
    - 8088:8088
    - 8089:8089
    - 9997:9997
    environment:
    - DONT_TIMEOUT=1
    - CRIBL_ROUTING_DEMO=1
