version: "3.5"
services:
  gogen:
    build:
      context: gogen
    command: start-training
  cribl:
    build:
      context: cribl
    ports:
    - 10200:10200
    - 10088:10088
    - 10080:10080
    - 10001:10001
    - 9999:9999
    - 9000:9000
    - 8125:8125
    - 8125:8125/udp
    - 5140:5140
    volumes:
    - ./cribl/cribl:/opt/cribl/local/cribl
    cap_add:
    - NET_ADMIN
    privileged: true
  splunk:
    build:
      context: splunk
    ports:
    - 8000:8000
    - 8088:8088
    - 8089:8089
    - 9997:9997
    environment:
    - DONT_TIMEOUT=1
    - CRIBL_ROUTING_DEMO=1
